### PR TITLE
Add new properties: left, text-stroke, and top

### PR DESCRIPTION
**Pull request by christabor**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi there,

Thanks for the contribution! However, I’m afraid I can’t merge this. top already exists, left is too similar and text-stroke is non-standard...

**Comment by christabor** [comment]
Thanks! I was hoping to add something new, but there are no instructions on what is standard, or what is preferred. Do you have a reference guide or plan on adding a readme for rules in the future?

**Comment by LeaVerou** [comment]
Hi Chris,

I’m referring to web standards not something I made up that I need to document. text-stroke is a proprietary WebKit extension.

**Comment by christabor** [comment]
Oh, I meant in general, like a shorthand guide of current css specs (something like http://www.css3.info/preview, or the full spec itself: http://www.w3.org/Style/CSS/specs.en.html. Also, documentation on rules such as "no non-visual elements" or "limit to no more than two examples per property" might be beneficial for contributors.

**Pull request closed without merging**
