### PR TITLE
Add 'box-shadow' transition with a glowing effect.

### PR DESCRIPTION
**Pull request by akai**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks for your submission!

However, isn't that very similar to http://leaverou.github.com/animatable/#box-shadow/3 ?
(haven't actually tried it, just looked at the code)

**Comment by akai** [comment]
Oh, before I commits this, that also didn't. 

And why not have a look this effect? If the background color is dark, it is really nice.

**Comment by LeaVerou** [comment]
Just took a look. It's nice, but very similar to existing box-shadow transitions, the core idea at least. I'm sorry :(

But thank you very much for taking the time to submit this! 
If you submit others in the future, keep in mind that they are alphabetically ordered by property and chronologically ordered inside the same property.

**Comment by akai** [comment]
OK. Thank you for the work!

**Pull request closed without merging**
