### PR TITLE
Should be ok now? Please forgive, as I am a novice at Github. Thanks.

### PR DESCRIPTION
**Pull request by steno**

### CODE REVIEW

**Comment by LeaVerou** [comment]
It's still there, on line 25. :( Just click on the commit above and you'll see it too.
I could fix it myself, but it would show up in the history as a change, and it wasn't one.

Don't worry about being a Github novice, I'm not very good with it myself. :)

**Comment by steno** [comment]
On line 25  I see a (-) sign showing that I removed wrong indent and new one added with tab (+)? what am I doing wrong? :(

**Comment by LeaVerou** [comment]
I think you're just using an editor that is configured for spaces instead of tabs and you probably tried something on that line so it converted the tab to spaces. 

Merged :)

**Comment by steno** [comment]
OK thanks Lea. Keep up the awesomeness! ;)

**Comment by LeaVerou** [comment]
Aaand it's live: http://leaverou.github.com/animatable/#padding

Thanks for the submission!

**Comment by steno** [comment]
Yay! :)

**Pull request merged**
