### PR TITLE
Added 'flip diagonal' transition on rotate3d

### PR DESCRIPTION
**Pull request by bartaz**
Flipping box around diagonal using rotate3d

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hawt stuff!!

But you didn't add it as the last transform demo :( 
Could you, please?

**Comment by bartaz** [comment]
Done!

**Comment by LeaVerou** [comment]
Now git doesn't let me merge it, either automatically or through the command line :( Ugh, I hate git sometimes. 

Would it be too much to ask you to submit a new pull request?

**Comment by bartaz** [comment]
I merged these commits into one, hopefully it won't mess it even more.

Can you try merging now?

**Comment by LeaVerou** [comment]
No, git still gives me shit :(

**Comment by bartaz** [comment]
Yet another try :)

I merged with your latest version. There was a conflict with my 'abyss' animation, as that was also the last transform one.
Hopefully now it will work fine.

**Pull request merged**
